-- Demo dataset for EV Journey (Northern Thailand)
-- Safe to re-run: uses upsert and clears only the demo agent ids.
SET client_encoding = 'UTF8';
CREATE EXTENSION IF NOT EXISTS postgis;

-- Provinces (base list referenced by the app)
INSERT INTO provinces (slug_en, name_th) VALUES
  ('chiang-mai', 'เชียงใหม่'),
  ('lamphun', 'ลำพูน'),
  ('lampang', 'ลำปาง'),
  ('mae-hong-son', 'แม่ฮ่องสอน')
ON CONFLICT (slug_en) DO UPDATE SET name_th = EXCLUDED.name_th;

-- Clean previous demo rows so the script can be re-run
DELETE FROM agent_logs WHERE agent_id IN (9001, 9002);
DELETE FROM agent_routes WHERE agent_id IN (9001, 9002);
DELETE FROM agents WHERE id IN (9001, 9002);
DELETE FROM chargers WHERE id IN ('demo-cnx-old-town', 'demo-cnx-airport-ac', 'demo-lpn-riverside', 'demo-lpg-night-bazaar', 'demo-mhs-airport');
DELETE FROM foods WHERE id IN ('demo-food-khaosoi', 'demo-food-lamphun-noodle', 'demo-food-lampang-steak', 'demo-food-mhs-pai');
DELETE FROM cafes WHERE id IN ('demo-cafe-ristr8to', 'demo-cafe-lpn-rimping', 'demo-cafe-lpg-kadkongta', 'demo-cafe-pai-canyon');
DELETE FROM hotels WHERE id IN ('demo-hotel-chiangmai-orchid', 'demo-hotel-lamphun-river', 'demo-hotel-lampang-green', 'demo-hotel-mhs-river');
DELETE FROM attractions WHERE id IN ('demo-at-cnx-suthep', 'demo-at-lpn-bridge', 'demo-at-lpg-temple', 'demo-at-mhs-pai-canyon');

-- Chargers
INSERT INTO chargers (id, name, type, kw, capacity, lat, lon, province_id, brand, address) VALUES
  ('demo-cnx-old-town', 'EV Station Nimman', 'DC', 60, 4, 18.7961, 98.9668, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'PTT EV Station', 'นิมมาน ซอย 9 เมืองเชียงใหม่'),
  ('demo-cnx-airport-ac', 'AC Wallbox Chiang Mai Airport', 'AC', 22, 2, 18.7668, 98.9629, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'EA Anywhere', 'ที่จอดรถสนามบินเชียงใหม่'),
  ('demo-lpn-riverside', 'Lamphun Riverside Charger', 'DC', 50, 2, 18.5777, 99.0083, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'PEA VOLTA', 'ริมแม่น้ำปิง ตัวเมืองลำพูน'),
  ('demo-lpg-night-bazaar', 'Lampang Night Bazaar Station', 'AC', 11, 3, 18.2875, 99.4920, (SELECT id FROM provinces WHERE slug_en='lampang'), 'MEA EV', 'กาดกองต้า ลำปาง'),
  ('demo-mhs-airport', 'Mae Hong Son Airport Fast', 'DC', 50, 2, 19.3010, 97.9750, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'PTT EV Station', 'สนามบินแม่ฮ่องสอน'),
  ('demo-lpg-pea-caltex-sopprap', 'PEA VOLTA คาลเท็กซ์ สบปราบ', 'DC', 120, 2, 17.907312, 99.342187, (SELECT id FROM provinces WHERE slug_en='lampang'), 'PEA VOLTA', 'คาลเท็กซ์ สบปราบ'),
  ('demo-lpg-pea-bangchak-sopprap', 'PEA VOLTA บางจาก สบปราบ #2', 'DC', 50, 2, 17.902313, 99.340812, (SELECT id FROM provinces WHERE slug_en='lampang'), 'PEA VOLTA', 'บางจาก สบปราบ'),
  ('demo-lpg-pea-bangchak-hangchat', 'PEA VOLTA บางจาก ห้างฉัตร #2', 'DC', 50, 2, 18.310688, 99.389938, (SELECT id FROM provinces WHERE slug_en='lampang'), 'PEA VOLTA', 'บางจาก ห้างฉัตร'),
  ('demo-lpg-eleza-coco', 'The Coco Lampang (EleXA)', 'DC', 60, 2, 18.134563, 99.391188, (SELECT id FROM provinces WHERE slug_en='lampang'), 'EleXA', 'เดอะโคโค่ ลำปาง'),
  ('demo-lpg-mg-thailand', 'บริษัท ทริปเปิล ที มอเตอร์ จำกัด (MG Thailand)', 'DC', 120, 2, 18.2538308, 99.4568609, (SELECT id FROM provinces WHERE slug_en='lampang'), 'MG Thailand', 'โชว์รูม MG ลำปาง'),
  ('demo-lpg-evpluz-bigc', 'บิ๊กซี ลำปาง (EV Station PluZ)', 'DC', 120, 2, 18.275688, 99.482563, (SELECT id FROM provinces WHERE slug_en='lampang'), 'EV Station PluZ', 'บิ๊กซี ลำปาง'),
  ('demo-lpg-evpluz-cs2018', 'พีทีที สเตชั่น บจ.ซีเอส 2018 ออยล์ (EV Station PluZ)', 'DC', 120, 2, 17.95375, 99.35125, (SELECT id FROM provinces WHERE slug_en='lampang'), 'EV Station PluZ', 'อ.เกาะคา'),
  ('demo-lpg-evpluz-th1994-out', 'พีทีที สเตชั่น บจ.ธ.1994 ปิโตรเลียม (EV Station PluZ) ขาออก', 'DC', 120, 2, 17.619813, 99.233812, (SELECT id FROM provinces WHERE slug_en='lampang'), 'EV Station PluZ', 'อ.สบปราบ (ขาออก)'),
  ('demo-lpg-evpluz-th1994-in', 'พีทีที สเตชั่น บจ.ธ.1994 ปิโตรเลียม (EV Station PluZ) ขาเข้า', 'DC', 120, 2, 17.618563, 99.234313, (SELECT id FROM provinces WHERE slug_en='lampang'), 'EV Station PluZ', 'อ.สบปราบ (ขาเข้า)'),
  ('demo-cnx-chg-ptt-maetang', 'สถานีชาร์จรถไฟฟ้า PTT EV Station Pluz แม่แตง', 'DC', 180, 2, 19.082187, 98.936188, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'PTT EV Station Pluz', 'อ.แม่แตง'),
  ('demo-cnx-chg-hkh-maerim', 'HKH Residence แม่ริม', 'DC', 50, 2, 18.908938, 98.904313, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'HKH Residence', 'อ.แม่ริม'),
  ('demo-cnx-chg-pea-maerim-ac', 'สถานีชาร์จ PEA VOLTA แม่ริม (AC)', 'AC', 43, 1, 18.901313, 98.949938, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'PEA VOLTA', 'อ.แม่ริม'),
  ('demo-cnx-chg-pea-maerim-dc', 'สถานีชาร์จ PEA VOLTA แม่ริม (DC)', 'DC', 50, 3, 18.901313, 98.949938, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'PEA VOLTA', 'อ.แม่ริม'),
  ('demo-cnx-chg-pluz-maerim-dc', 'สถานีชาร์จ ev station pluz แม่ริม (DC)', 'DC', 120, 2, 18.921563, 98.940438, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'EV Station Pluz', 'อ.แม่ริม'),
  ('demo-cnx-chg-pluz-maerim-ac', 'สถานีชาร์จ ev station pluz แม่ริม (AC)', 'AC', 22, 1, 18.921563, 98.940438, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'EV Station Pluz', 'อ.แม่ริม'),
  ('demo-cnx-chg-evolt-chomthong', 'สถานีชาร์จ Evolt จอมทอง', 'DC', 150, 2, 18.450812, 98.740688, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'Evolt', 'อ.จอมทอง'),
  ('demo-cnx-chg-smile-chomthong', 'สถานีชาร์จ Smile จอมทอง', 'AC', 22, 2, 18.415937, 98.677437, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'Smile', 'อ.จอมทอง'),
  ('demo-cnx-chg-altervim-chomthong-dc', 'สถานีชาร์จ Altervim จอมทอง (DC)', 'DC', 60, 2, 18.429437, 98.681562, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'Altervim', 'อ.จอมทอง'),
  ('demo-cnx-chg-altervim-chomthong-ac', 'สถานีชาร์จ Altervim จอมทอง (AC)', 'AC', 3, 1, 18.429437, 98.681562, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'Altervim', 'อ.จอมทอง'),
  ('demo-cnx-chg-ptt-chomthong', 'สถานีชาร์จรถไฟฟ้า PTT EV Station Pluz จอมทอง', 'DC', 120, 2, 18.435938, 98.687813, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'PTT EV Station Pluz', 'อ.จอมทอง'),
  ('demo-cnx-chg-pea-doisaket-ac', 'สถานีชาร์จ PEA VOLTA ดอยสะเก็ด (AC)', 'AC', 43, 1, 18.873438, 99.133813, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'PEA VOLTA', 'อ.ดอยสะเก็ด'),
  ('demo-cnx-chg-pea-doisaket-dc', 'สถานีชาร์จ PEA VOLTA ดอยสะเก็ด (DC)', 'DC', 50, 4, 18.873438, 99.133813, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'PEA VOLTA', 'อ.ดอยสะเก็ด'),
  ('demo-cnx-chg-evolt-sansai', 'สถานีชาร์จ Evolt สันทราย', 'DC', 150, 2, 18.852562, 99.090812, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'Evolt', 'อ.สันทราย'),
  ('demo-cnx-chg-tony-doisaket', 'สถานีชาร์จ Tony+Patrick ดอยสะเก็ด', 'DC', 50, 1, 18.882062, 99.149187, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'Tony+Patrick', 'อ.ดอยสะเก็ด'),
  ('demo-cnx-chg-denza-muang', 'Denza Dynasty Chiangmai อ.เมืองเชียงใหม่', 'DC', 120, 4, 18.768062, 98.982062, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'Denza', 'อ.เมืองเชียงใหม่'),
  ('demo-lpn-chg-dohome', 'DoHome Lamphun (AC)', 'AC', 22, 2, 18.602187, 99.023062, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'DoHome', 'ใกล้ดอยติ ลำพูน'),
  ('demo-lpn-chg-cnxauto', 'บริษัท ซีเอ็นเอ็กซ์ ออโต้ จำกัด (สาขาลำพูน)', 'DC', 120, 2, 18.603813, 99.022312, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'CNX Auto', 'สาขาลำพูน'),
  ('demo-lpn-chg-pea-jaemfa', 'PEA VOLTA แจ่มฟ้า เมืองลำพูน', 'DC', 26, 2, 18.558937, 99.039187, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'PEA VOLTA', 'ห้างแจ่มฟ้า'),
  ('demo-lpn-chg-pt-station', 'พีทีที สเตชั่น หจก.ช.ชญาปิโตรเลียม', 'DC', 120, 2, 18.570813, 99.044687, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'PTT EV Station', 'เมืองลำพูน'),
  ('demo-lpn-chg-gentari-caltex', 'Gentari Caltex (Charoenkit) ลำพูน', 'DC', 120, 2, 18.542437, 99.063187, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'Gentari', 'คาลเท็กซ์ ลำพูน'),
  ('demo-lpn-chg-pt-lamphun2', 'สถานีบริการน้ำมัน PT ลำพูน 2', 'DC', 150, 2, 18.546062, 99.059188, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'PT', 'ลำพูน'),
  ('demo-lpn-chg-ptt-doiti', 'พีทีที สเตชั่น สาขาลำพูน-ดอยติ', 'DC', 120, 2, 18.56625, 99.02875, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'PTT EV Station', 'ดอยติ'),
  ('demo-lpn-chg-byd-northstar', 'BYD North Star Lamphun', 'DC', 120, 2, 18.570188, 99.043813, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'BYD', 'ลำพูน'),
  ('demo-lpn-chg-pepsi', 'Pepsi-Cola (Thai) Trading ลำพูน', 'DC', 22, 3, 18.618812, 99.047313, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'Pepsi', 'โรงงานเพ็ปซี่ ลำพูน'),
  ('demo-mhs-chg-tiwdoigarden', 'ทิวดอยการ์เด้น รีสอร์ทปาย', 'AC', 7, 2, 19.338188, 98.432063, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'Resort', 'ปาย'),
  ('demo-mhs-chg-ptt-sukhum-dc', 'พีทีที สเตชั่น บจ.สุขุมเซอร์วิส (DC)', 'DC', 120, 2, 19.293406, 97.964213, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'PTT EV Station', 'อ.เมืองแม่ฮ่องสอน'),
  ('demo-mhs-chg-ptt-sukhum-ac', 'พีทีที สเตชั่น บจ.สุขุมเซอร์วิส (AC)', 'AC', 22, 1, 19.293406, 97.964213, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'PTT EV Station', 'อ.เมืองแม่ฮ่องสอน'),
  ('demo-mhs-chg-elexa-mhs', 'สถานี EleXA แม่ฮ่องสอน', 'DC', 125, 2, 19.292063, 97.964812, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'EleXA', 'อ.เมืองแม่ฮ่องสอน'),
  ('demo-mhs-chg-elexa-pai', 'สถานี EleXA ปาย', 'DC', 120, 2, 19.348727, 98.442399, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'EleXA', 'ปาย'),
  ('demo-mhs-chg-silhouette', 'Silhouette by Reverie Siam', 'DC', 120, 2, 19.348687, 98.442312, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'Reverie Siam', 'ปาย'),
  ('demo-mhs-chg-pea-pai', 'PEA VOLTA ปาย', 'DC', 120, 2, 19.363108, 98.425043, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'PEA VOLTA', 'ปาย'),
  ('demo-mhs-chg-foofu', 'ร้านฟูฟู่หมาล่าสายพาน', 'AC', 7, 2, 19.370938, 98.403688, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'Foofu', 'ปาย'),
  ('demo-mhs-chg-pea-mueang', 'PEA VOLTA เมืองแม่ฮ่องสอน', 'DC', 60, 2, 19.315088, 97.965639, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'PEA VOLTA', 'อ.เมืองแม่ฮ่องสอน')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  type = EXCLUDED.type,
  kw = EXCLUDED.kw,
  capacity = EXCLUDED.capacity,
  lat = EXCLUDED.lat,
  lon = EXCLUDED.lon,
  province_id = EXCLUDED.province_id,
  brand = EXCLUDED.brand,
  address = EXCLUDED.address;

-- Attractions (keep small but enough to show the UI)
INSERT INTO attractions (id, name_th, name_en, kind, lat, lon, province_id, source_id, address_th, province_th, type_th, detail_th) VALUES
  ('demo-at-cnx-suthep', 'วัดพระธาตุดอยสุเทพ', 'Doi Suthep Temple', 'CTA', 18.8040, 98.9210, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'cnx-001', 'ดอยสุเทพ เมืองเชียงใหม่', 'เชียงใหม่', 'วัด / จุดชมวิว', 'วัดคู่เมืองเชียงใหม่ เห็นวิวเมืองเต็มตา'),
  ('demo-at-lpn-bridge', 'ขัวเหล็กทาชมภู', 'Tha Chomphu Bridge', 'NTA', 18.4280, 99.1490, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'lpn-001', 'อ.แม่ทา จ.ลำพูน', 'ลำพูน', 'สะพาน', 'สะพานโค้งสีขาว เหมาะกับการถ่ายรูป'),
  ('demo-at-lpg-temple', 'วัดพระธาตุลำปางหลวง', 'Wat Phra That Lampang Luang', 'CTA', 18.2050, 99.4000, (SELECT id FROM provinces WHERE slug_en='lampang'), 'lpg-001', 'เกาะคา ลำปาง', 'ลำปาง', 'วัด', 'วัดเก่าแก่ สถาปัตยกรรมล้านนา'),
  ('demo-at-mhs-pai-canyon', 'ปายแคนยอน', 'Pai Canyon', 'AVT', 19.3620, 98.4470, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'mhs-001', 'อ.ปาย จ.แม่ฮ่องสอน', 'แม่ฮ่องสอน', 'เส้นทางธรรมชาติ', 'จุดชมวิวพระอาทิตย์ตกชื่อดัง'),
  ('demo-at-cnx-oasis-nimman', 'โอเอซิสสปา แอท นิมมาน', 'Oasis Spa at Nimman', 'CTA', 18.798313, 98.968187, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'cnx-at-002', 'ย่านนิมมาน', 'เชียงใหม่', 'แหล่งท่องเที่ยวสำหรับกิจกรรมพิเศษ นันทนาการ และความสนใจพิเศษ', 'เปิด 10:00-24:00'),
  ('demo-at-cnx-maekampong', 'หมู่บ้านแม่กำปอง', 'Mae Kampong Village', 'NTA', 18.8655073, 99.3509846, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'cnx-at-003', 'แม่ออน', 'เชียงใหม่', 'แหล่งท่องเที่ยวทางธรรมชาติ', 'หมู่บ้านโฮมสเตย์กลางหุบเขา'),
  ('demo-at-cnx-architecture', 'ศูนย์สถาปัตยกรรมล้านนา คุ้มเจ้าบุรีรัตน์ มหาอินทร์', 'Lanna Architecture Center', 'CTA', 18.7879488, 98.988302, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'cnx-at-004', 'ย่านเวียงกุมกาม', 'เชียงใหม่', 'แหล่งท่องเที่ยวทางประวัติศาสตร์ และวัฒนธรรม', 'คุ้มโบราณจัดแสดงสถาปัตยกรรมล้านนา'),
  ('demo-at-cnx-letsrelax', 'เล็ทส์ รีแลกซ์ วัน นิมมาน เชียงใหม่', 'Let''s Relax One Nimman', 'CTA', 18.799337, 98.967331, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'cnx-at-005', 'วันนิมมาน', 'เชียงใหม่', 'แหล่งท่องเที่ยวสำหรับกิจกรรมพิเศษ นันทนาการ และความสนใจพิเศษ', 'สปากลางเมือง'),
  ('demo-at-cnx-oasis-lanna', 'ดิ โอเอซิสสปา ลานนา', 'Oasis Spa Lanna', 'CTA', 18.7872785, 98.9823119, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'cnx-at-006', 'ถนนสมโภชเชียงใหม่ 700 ปี', 'เชียงใหม่', 'แหล่งท่องเที่ยวสำหรับกิจกรรมพิเศษ นันทนาการ และความสนใจพิเศษ', 'สปาเรือนไม้แบบลานนา'),
  ('demo-at-cnx-leela-thapae', 'ลีลานวดไท ท่าแพ', 'Leela Thai Massage Thapae', 'CTA', 18.7877555, 98.9924697, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'cnx-at-007', 'ถนนท่าแพ', 'เชียงใหม่', 'แหล่งท่องเที่ยวสำหรับกิจกรรมพิเศษ นันทนาการ และความสนใจพิเศษ', 'นวดแผนไทยใจกลางคูเมือง'),
  ('demo-at-cnx-leela-jediluang', 'ลีลานวดไท เจดีย์หลวง', 'Leela Thai Massage Jediluang', 'CTA', 18.7874416, 98.9881324, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), 'cnx-at-008', 'วัดเจดีย์หลวง', 'เชียงใหม่', 'แหล่งท่องเที่ยวสำหรับกิจกรรมพิเศษ นันทนาการ และความสนใจพิเศษ', 'นวดผ่อนคลายใกล้วัดเจดีย์หลวง'),
  ('demo-at-lpg-chaeson', 'อุทยานแห่งชาติแจ้ซ้อน', 'Chae Son National Park', 'NTA', 18.836605, 99.47068, (SELECT id FROM provinces WHERE slug_en='lampang'), 'lpg-at-002', 'อ.เมืองปาน', 'ลำปาง', 'แหล่งท่องเที่ยวทางธรรมชาติ', 'เปิด 08:00-16:18'),
  ('demo-at-lpg-ban-ma-tha-nam', 'บ้านม้าท่าน้ำ', 'Ban Ma Tha Nam', 'CTA', 18.296671, 99.5123346, (SELECT id FROM provinces WHERE slug_en='lampang'), 'lpg-at-003', 'อ.เมืองลำปาง', 'ลำปาง', 'แหล่งท่องเที่ยวทางประวัติศาสตร์ และวัฒนธรรม', 'ชุมชนริมแม่น้ำ'),
  ('demo-at-lpg-wat-wiang', 'วัดเวียง', 'Wat Wiang', 'CTA', 17.6260871, 99.2264885, (SELECT id FROM provinces WHERE slug_en='lampang'), 'lpg-at-004', 'สบปราบ', 'ลำปาง', 'แหล่งท่องเที่ยวทางประวัติศาสตร์ และวัฒนธรรม', 'วัดเก่าแก่ในชุมชน'),
  ('demo-at-lpg-mae-kham', 'อ่างเก็บน้ำแม่ขาม', 'Mae Kham Reservoir', 'NTA', 18.3755556, 99.7619444, (SELECT id FROM provinces WHERE slug_en='lampang'), 'lpg-at-005', 'เถิน', 'ลำปาง', 'แหล่งท่องเที่ยวทางธรรมชาติ', 'อ่างเก็บน้ำวิวภูเขา'),
  ('demo-at-lpg-doiprachan', 'วัดพระธาตุดอยพระฌาน', 'Wat Phra That Doi Phra Chan', 'CTA', 18.1111001, 99.4712379, (SELECT id FROM provinces WHERE slug_en='lampang'), 'lpg-at-006', 'แม่ทะ', 'ลำปาง', 'แหล่งท่องเที่ยวทางประวัติศาสตร์ และวัฒนธรรม', 'วัดบนยอดดอยวิวสวย'),
  ('demo-at-lpg-kaofu', 'น้ำตกเกาฟุ', 'Kao Fu Waterfall', 'NTA', 18.7499355, 99.8094848, (SELECT id FROM provinces WHERE slug_en='lampang'), 'lpg-at-007', 'งาว', 'ลำปาง', 'แหล่งท่องเที่ยวทางธรรมชาติ', 'น้ำตกท่ามกลางป่า'),
  ('demo-at-lpg-anchalee', 'อัญชลี แกลลอรี่', 'Anchalee Gallery', 'CTA', 18.2670841, 99.5252639, (SELECT id FROM provinces WHERE slug_en='lampang'), 'lpg-at-008', 'เมืองลำปาง', 'ลำปาง', 'แหล่งท่องเที่ยวทางประวัติศาสตร์ และวัฒนธรรม', 'แกลเลอรีศิลปะท้องถิ่น'),
  ('demo-at-lpg-community-dev', 'ศูนย์ศึกษาและพัฒนาชุมชนลำปาง', 'Lampang Community Development Center', 'CTA', 18.2935847, 99.4202936, (SELECT id FROM provinces WHERE slug_en='lampang'), 'lpg-at-009', 'ห้างฉัตร', 'ลำปาง', 'แหล่งท่องเที่ยวทางประวัติศาสตร์ และวัฒนธรรม', 'ศูนย์การเรียนรู้ชุมชน'),
  ('demo-at-lpg-kohpai', 'ศูนย์การเรียนรู้ กอไผ่เซรามิค', 'Koh Pai Ceramic Learning Center', 'CTA', 18.2548611, 99.4451173, (SELECT id FROM provinces WHERE slug_en='lampang'), 'lpg-at-010', 'ห้างฉัตร', 'ลำปาง', 'แหล่งท่องเที่ยวทางประวัติศาสตร์ และวัฒนธรรม', 'เวิร์กช็อปเซรามิก'),
  ('demo-at-lpn-maemoei', 'อ่างเก็บน้ำแม่เมย', 'Mae Moei Reservoir', 'NTA', 18.3538871, 98.9569582, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'lpn-at-002', 'อ.ลี้', 'ลำพูน', 'แหล่งท่องเที่ยวทางธรรมชาติ', 'เปิด 08:00-17:00'),
  ('demo-at-lpn-thaisilk', 'ลำพูนไหมไทย', 'Lamphun Thai Silk', 'CTA', 18.5706798, 99.0149139, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'lpn-at-003', 'เมืองลำพูน', 'ลำพูน', 'แหล่งท่องเที่ยวทางประวัติศาสตร์ และวัฒนธรรม', 'แหล่งผ้าไหมไทย'),
  ('demo-at-lpn-ptfarm', 'พี.ที.ฟาร์ม', 'P.T. Farm', 'CTA', 18.5496438, 98.976258, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'lpn-at-004', 'ลี้', 'ลำพูน', 'แหล่งท่องเที่ยวสำหรับกิจกรรมพิเศษ นันทนาการ และความสนใจพิเศษ', 'ฟาร์มท่องเที่ยว'),
  ('demo-at-lpn-walking', 'ข่วงคนเตียวหละปูน (ถนนคนเดินลำพูน)', 'Lamphun Walking Street', 'CTA', 18.5778026, 99.0092697, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'lpn-at-005', 'เมืองลำพูน', 'ลำพูน', 'แหล่งท่องเที่ยวทางประวัติศาสตร์ และวัฒนธรรม', 'เปิด 16:00-20:18'),
  ('demo-at-lpn-museum', 'พิพิธภัณฑสถานแห่งชาติหริภุญไชย', 'Hariphunchai National Museum', 'CTA', 18.5771378, 99.0066412, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'lpn-at-006', 'เมืองลำพูน', 'ลำพูน', 'แหล่งท่องเที่ยวทางประวัติศาสตร์ และวัฒนธรรม', 'พิพิธภัณฑ์เมืองลำพูน'),
  ('demo-at-lpn-sala-laoleuang', 'หอศิลป์ สล่าเลาเลือง', 'Sala Laoleuang Art Gallery', 'CTA', 18.5602946, 98.992394, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'lpn-at-007', 'เมืองลำพูน', 'ลำพูน', 'แหล่งท่องเที่ยวทางประวัติศาสตร์ และวัฒนธรรม', 'แกลเลอรีท้องถิ่น'),
  ('demo-at-lpn-phabat-huaitom', 'ชุมชนพระบาทห้วยต้ม', 'Phra Bat Huai Tom Community', 'CTA', 17.7283948, 98.9542061, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'lpn-at-008', 'ลี้', 'ลำพูน', 'แหล่งท่องเที่ยวทางประวัติศาสตร์ และวัฒนธรรม', 'ชุมชนชาวกะเหรี่ยง'),
  ('demo-at-lpn-tapanrak', 'ทาปันรักษ์', 'Tha Pan Rak', 'CTA', 18.4481295, 99.1347392, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'lpn-at-009', 'ทาปลาดุก', 'ลำพูน', 'แหล่งท่องเที่ยวสำหรับกิจกรรมพิเศษ นันทนาการ และความสนใจพิเศษ', 'แหล่งเรียนรู้ชุมชน'),
  ('demo-at-lpn-phanam', 'วัดพระพุทรบาทผาหนาม', 'Wat Phra Phutthabat Pha Nam', 'CTA', 17.8355385, 98.9250593, (SELECT id FROM provinces WHERE slug_en='lamphun'), 'lpn-at-010', 'ทุ่งหัวช้าง', 'ลำพูน', 'แหล่งท่องเที่ยวทางประวัติศาสตร์ และวัฒนธรรม', 'วัดบนหน้าผา วิวสวย'),
  ('demo-at-mhs-sappaya', 'สัปปายยะ สปา', 'Sappaya Spa', 'CTA', 19.3523575, 98.4421915, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'mhs-at-002', 'ปาย', 'แม่ฮ่องสอน', 'แหล่งท่องเที่ยวสำหรับกิจกรรมพิเศษ นันทนาการ และความสนใจพิเศษ', 'สปาเปิด 10:00-21:00'),
  ('demo-at-mhs-norhorfa', 'จุดชมวิว หน่อ-ฮ่อ-ฝ่า', 'Nor Hor Fa Viewpoint', 'NTA', 19.548178, 98.1601458, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'mhs-at-003', 'แม่ลาน้อย', 'แม่ฮ่องสอน', 'แหล่งท่องเที่ยวทางธรรมชาติ', 'จุดชมวิวเทือกเขา'),
  ('demo-at-mhs-yunlai', 'ทะเลหมอกหยุนไหล', 'Yun Lai Viewpoint', 'NTA', 19.3690372, 98.395388, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'mhs-at-004', 'ปาย', 'แม่ฮ่องสอน', 'แหล่งท่องเที่ยวทางธรรมชาติ', 'จุดชมทะเลหมอก'),
  ('demo-at-mhs-klo-selo', 'กลอเซโล', 'Klo Selo', 'NTA', 17.8754945, 97.7134316, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'mhs-at-005', 'แม่สะเรียง', 'แม่ฮ่องสอน', 'แหล่งท่องเที่ยวทางธรรมชาติ', 'หมู่บ้านกะเหรี่ยงกลางหุบเขา'),
  ('demo-at-mhs-doi-thong', 'ดอยธง', 'Doi Thong', 'NTA', 19.3446878, 98.3306995, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'mhs-at-006', 'ปาย', 'แม่ฮ่องสอน', 'แหล่งท่องเที่ยวทางธรรมชาติ', 'จุดชมวิวป่าเขา'),
  ('demo-at-mhs-doi-miang', 'ดอยเมี่ยง', 'Doi Miang', 'NTA', 19.3261042, 98.3453708, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'mhs-at-007', 'ปาย', 'แม่ฮ่องสอน', 'แหล่งท่องเที่ยวทางธรรมชาติ', 'ดอยวิวสวย'),
  ('demo-at-mhs-saphan-bunkho', 'สะพานบุญโขกู้โส่', 'Boong Ko Ku So Bridge', 'CTA', 19.3225079, 98.3931658, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'mhs-at-008', 'ปาย', 'แม่ฮ่องสอน', 'แหล่งท่องเที่ยวทางประวัติศาสตร์ และวัฒนธรรม', 'สะพานไม้ไผ่'),
  ('demo-at-mhs-gikokor', 'จุดชมวิวกิกอคอบ้านห้วยเฮี๊ยะ', 'Gik O Kor Viewpoint', 'NTA', 19.6620182, 98.2378438, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'mhs-at-009', 'ขุนยวม', 'แม่ฮ่องสอน', 'แหล่งท่องเที่ยวทางธรรมชาติ', 'ชมทะเลหมอก'),
  ('demo-at-mhs-san-wo-to', 'จุดชมวิวสันวัวตอ', 'San Wua To Viewpoint', 'NTA', 19.5998424, 98.2552645, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), 'mhs-at-010', 'ปางมะผ้า', 'แม่ฮ่องสอน', 'แหล่งท่องเที่ยวทางธรรมชาติ', 'จุดชมวิวภูเขา')
ON CONFLICT (id) DO UPDATE SET
  name_th = EXCLUDED.name_th,
  name_en = EXCLUDED.name_en,
  kind = EXCLUDED.kind,
  lat = EXCLUDED.lat,
  lon = EXCLUDED.lon,
  province_id = EXCLUDED.province_id,
  source_id = EXCLUDED.source_id,
  address_th = EXCLUDED.address_th,
  province_th = EXCLUDED.province_th,
  type_th = EXCLUDED.type_th,
  detail_th = EXCLUDED.detail_th;

-- Food
INSERT INTO foods (id, name_th, name_en, price_range, lat, lon, province_id, open_hours_json) VALUES
  ('demo-food-khaosoi', 'ข้าวซอยแม่สาย', 'Khao Soi Mae Sai', '80-150', 18.7940, 98.9890, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), '{"open":"10:00","close":"17:00"}'),
  ('demo-food-lamphun-noodle', 'ก๋วยเตี๋ยวห้วยม้า', 'Lamphun Noodle House', '50-120', 18.5740, 99.0150, (SELECT id FROM provinces WHERE slug_en='lamphun'), '{"open":"08:00","close":"16:00"}'),
  ('demo-food-lampang-steak', 'บ้านไร่สเต็ก', 'Farmhouse Steak Lampang', '120-250', 18.2870, 99.4920, (SELECT id FROM provinces WHERE slug_en='lampang'), '{"open":"11:00","close":"21:00"}'),
  ('demo-food-mhs-pai', 'ข้าวซอยปายริเวอร์', 'Pai River Khao Soi', '90-180', 19.3610, 98.4430, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), '{"open":"09:30","close":"19:00"}'),
  ('demo-food-cnx-mianjakin', 'มีอันจะกิน', 'Mian Ja Kin', NULL, 18.761988, 99.001615, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), '{"open":"10:00","close":"00:00"}'),
  ('demo-food-cnx-samsenvilla', 'ร้านอาหาร สามเสนวิลล่า ริมปิง', 'Samsen Villa Rim Ping', NULL, 18.7942151, 99.0008869, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), '{"open":"11:00","close":"23:00"}'),
  ('demo-food-cnx-khey', 'เขยเจียงใหม่ - อาหารเหนือ', 'Khey Chiang Mai', NULL, 18.8004791, 98.9782729, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), '{"open":"11:00","close":"22:00"}'),
  ('demo-food-cnx-kaengrhon', 'แกงร้อนบ้านสวน', 'Kaeng Ron Ban Suan', NULL, 18.8210124, 98.9616793, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), '{"open":"10:00","close":"22:00"}'),
  ('demo-food-cnx-thakham', 'ท่าข้าม', 'Tha Kham', NULL, 18.7461954, 98.9533388, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), '{"open":"11:00","close":"22:00"}'),
  ('demo-food-cnx-chalong', 'ร้านครัวฉลองเชียงใหม่', 'Chalong Chiang Mai', NULL, 18.8292261, 98.9784442, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), '{"open":"10:00","close":"21:00"}'),
  ('demo-food-cnx-tongnuea', 'ร้านต๋องเหนือ / Tongnuea', 'Tongnuea', NULL, 18.7681571, 98.9842006, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), '{"open":"11:00","close":"22:00"}'),
  ('demo-food-cnx-baanmae', 'ร้านอาหาร บ้านแม่', 'Baan Mae', NULL, 18.8037903, 98.9724298, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), '{"open":"11:00","close":"22:00"}'),
  ('demo-food-cnx-comedara', 'ร้านอาหาร คำดารา comedara', 'Comedara', NULL, 18.7930324, 99.0009582, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), '{"open":"11:00","close":"22:00"}'),
  ('demo-food-cnx-khaosoi-chiangmai', 'ข้าวโซอิ', 'Khao Zoi', NULL, 18.8091471, 99.0047617, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), '{"open":"09:00","close":"20:00"}'),
  ('demo-food-lpg-chatsomboon', 'ครัวชาติสมบูรณ์ ChatSomBoon', 'ChatSomBoon', NULL, 18.2906545, 99.4832164, (SELECT id FROM provinces WHERE slug_en='lampang'), '{"open":"11:00","close":"21:00"}'),
  ('demo-food-lpg-aroi-baht', 'ร้านอร่อยบาทเดียว', 'Aroi Baht Deaw', NULL, 18.2897662, 99.4960241, (SELECT id FROM provinces WHERE slug_en='lampang'), '{"open":"16:00","close":"23:00"}'),
  ('demo-food-lpg-runway', 'ครัวรันเวย์', 'Runway Kitchen', NULL, 18.2823791, 99.5034408, (SELECT id FROM provinces WHERE slug_en='lampang'), '{"open":"10:30","close":"23:00"}'),
  ('demo-food-lpg-mukda', 'ครัวมุกดา', 'Krua Mukda', NULL, 18.2854797, 99.5045178, (SELECT id FROM provinces WHERE slug_en='lampang'), '{"open":"08:00","close":"15:00"}'),
  ('demo-food-lpg-baan-phraya', 'Baan Phraya Suren by Madame Musur', 'Baan Phraya Suren', NULL, 18.2835098, 99.4743368, (SELECT id FROM provinces WHERE slug_en='lampang'), '{"open":"10:00","close":"21:30"}'),
  ('demo-food-lpg-teppros', 'เทพรส 66', 'Teppros 66', NULL, 18.2864676, 99.4959429, (SELECT id FROM provinces WHERE slug_en='lampang'), '{"open":"08:00","close":"15:30"}'),
  ('demo-food-lpg-riverside', 'ร้านอาหารเดอะริเวอร์ไซด์ The Riverside Restaurant Lampang', 'The Riverside Restaurant Lampang', NULL, 18.290736, 99.493102, (SELECT id FROM provinces WHERE slug_en='lampang'), '{"open":"11:00","close":"23:00"}'),
  ('demo-food-lpg-ochawattana', 'ร้านโอชาวัฒนา', 'Ocha Wattana', NULL, 18.2800551, 99.482948, (SELECT id FROM provinces WHERE slug_en='lampang'), '{"open":"09:00","close":"14:00"}'),
  ('demo-food-lpg-superzapp', 'ร้านซุปเปอร์แซ่บ แนวกินอีสาน', 'Super Zapp Isan', NULL, 18.2817266, 99.477113, (SELECT id FROM provinces WHERE slug_en='lampang'), '{"open":"11:00","close":"22:00"}'),
  ('demo-food-lpn-mallila', 'มะลิลา', 'Mallila', NULL, 18.5813163, 99.0063786, (SELECT id FROM provinces WHERE slug_en='lamphun'), '{"open":"10:00","close":"20:00"}'),
  ('demo-food-lpn-dawkanong', 'ร้านอาหารดาวคะนอง สาขา ในเมือง', 'Dao Kanong City', NULL, 18.5893336, 99.0116282, (SELECT id FROM provinces WHERE slug_en='lamphun'), '{"open":"10:00","close":"20:00"}'),
  ('demo-food-lpn-kruawandee', 'ครัววันดี', 'Krua Wandee', NULL, 18.5916297, 98.9792783, (SELECT id FROM provinces WHERE slug_en='lamphun'), '{"open":"09:00","close":"21:00"}'),
  ('demo-food-lpn-lab-lung-nin', 'ร้าน ลาบลุงนิล', 'Lab Lung Nin', NULL, 18.569422, 99.0093938, (SELECT id FROM provinces WHERE slug_en='lamphun'), '{"open":"10:00","close":"23:00"}'),
  ('demo-food-lpn-kanomseng', 'ขนมเส้นหม้อดิน ลำพูน', 'Kanom Sen Modin Lamphun', NULL, 18.5559535, 99.0359139, (SELECT id FROM provinces WHERE slug_en='lamphun'), '{"open":"09:49","close":"15:59"}'),
  ('demo-food-lpn-khaosoi-lamyai', 'ร้าน บ้านข้าวซอยลำไย ลำพูน', 'Baan Khao Soi Lamyai', NULL, 18.5590021, 98.9856319, (SELECT id FROM provinces WHERE slug_en='lamphun'), '{"open":"08:30","close":"15:00"}'),
  ('demo-food-lpn-tonfai', 'ร้านต้นฝ้าย', 'Ton Fai', NULL, 18.5761862, 99.0091133, (SELECT id FROM provinces WHERE slug_en='lamphun'), '{"open":"11:00","close":"22:00"}'),
  ('demo-food-lpn-junpha', 'จันผา อาหารพื้นเมือง', 'Junpha Local Kitchen', NULL, 18.5693262, 98.9961509, (SELECT id FROM provinces WHERE slug_en='lamphun'), '{"open":"10:30","close":"20:00"}'),
  ('demo-food-lpn-dawkanong2', 'ร้านอาหารดาวคะนองลำพูน', 'Dao Kanong Lamphun', NULL, 18.5467059, 99.0580121, (SELECT id FROM provinces WHERE slug_en='lamphun'), '{"open":"08:30","close":"20:30"}'),
  ('demo-food-mhs-baifern', 'ร้านอาหารใบเฟิร์น', 'Bai Fern Restaurant', NULL, 19.2984188, 97.9657511, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), '{"open":"11:00","close":"21:00"}'),
  ('demo-food-mhs-baan-songthai', 'ร้านอาหารบ้านทรงไทย', 'Baan Song Thai', NULL, 19.2747494, 97.9506576, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), '{"open":"08:30","close":"16:00"}'),
  ('demo-food-mhs-1095-garden', 'ร้านอาหาร 1095 Garden', '1095 Garden', NULL, 19.3022234, 97.9794692, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), '{"open":"11:00","close":"23:00"}'),
  ('demo-food-mhs-kaimook', 'ร้านอาหารไข่มุก', 'Kaimook Restaurant', NULL, 19.3002257, 97.9660038, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), '{"open":"10:00","close":"21:00"}'),
  ('demo-food-mhs-krua-je-on', 'ก๋วยเตี๋ยวและอาหารตามสั่งครัวเจ๊ออน', 'Krua Je On', NULL, 19.2977412, 97.9654462, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), '{"open":"07:00","close":"20:00"}'),
  ('demo-food-mhs-tharn-hongsorn', 'สวนอาหาร ธารฮ่องสอน', 'Tharn Hongsorn', NULL, 19.3012374, 97.9501316, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), '{"open":"10:00","close":"23:00"}'),
  ('demo-food-mhs-liwine', 'ลีไวน์ อาหารจีนยูนาน', 'Lee Wine Yunnan', NULL, 19.5856386, 97.9426435, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), '{"open":"08:00","close":"20:00"}')
ON CONFLICT (id) DO UPDATE SET
  name_th = EXCLUDED.name_th,
  name_en = EXCLUDED.name_en,
  price_range = EXCLUDED.price_range,
  lat = EXCLUDED.lat,
  lon = EXCLUDED.lon,
  province_id = EXCLUDED.province_id,
  open_hours_json = EXCLUDED.open_hours_json;

-- Cafes
INSERT INTO cafes (id, name_th, name_en, lat, lon, province_id, open_hours_json) VALUES
  ('demo-cafe-ristr8to', 'Ristr8to นิมมาน', 'Ristr8to', 18.7963, 98.9679, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), '{"open":"08:00","close":"18:00"}'),
  ('demo-cafe-lpn-rimping', 'สวนไผ่ คาเฟ่', 'Lamphun Bamboo Cafe', 18.5820, 99.0170, (SELECT id FROM provinces WHERE slug_en='lamphun'), '{"open":"09:00","close":"17:00"}'),
  ('demo-cafe-lpg-kadkongta', 'กาดกองต้า คาเฟ่', 'Kad Kong Ta Cafe', 18.2960, 99.4930, (SELECT id FROM provinces WHERE slug_en='lampang'), '{"open":"08:30","close":"19:00"}'),
  ('demo-cafe-pai-canyon', 'คาเฟ่ปายแคนยอน', 'Pai Canyon Cafe', 19.3640, 98.4475, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), '{"open":"09:00","close":"18:30"}'),
  ('demo-cafe-cnx-gallery-drip', 'Gallery Drip Coffee Chiang Mai', 'Gallery Drip Coffee Chiang Mai', 18.7902126, 98.986684, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), NULL),
  ('demo-cafe-cnx-pegasus', 'Pegasus Café & Roastery', 'Pegasus Café & Roastery', 18.7852092, 98.9872138, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), NULL),
  ('demo-cafe-cnx-naps', 'Nap’s Coffee Roaster CNX', 'Nap’s Coffee Roaster CNX', 18.7895957, 98.9850092, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), NULL),
  ('demo-cafe-cnx-coolmuang', 'CoolMuang Coffee', 'CoolMuang Coffee', 18.788462, 98.993074, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), NULL),
  ('demo-cafe-cnx-omnia', 'Omnia Cafe & Roastery', 'Omnia Cafe & Roastery', 18.8135376, 98.9737113, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), NULL),
  ('demo-cafe-cnx-oasis', 'Cafe de Oasis', 'Cafe de Oasis', 18.8248767, 98.9596363, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), NULL),
  ('demo-cafe-cnx-fernforest', 'เฟิร์นฟอเรสต์คาเฟ่', 'Fern Forest Cafe', 18.7933635, 98.982022, (SELECT id FROM provinces WHERE slug_en='chiang-mai'), NULL),
  ('demo-cafe-lpg-otis', 'Otis Café', 'Otis Café', 18.356437, 99.545563, (SELECT id FROM provinces WHERE slug_en='lampang'), NULL),
  ('demo-cafe-lpg-mixirista', 'Mixirista Lampang', 'Mixirista Lampang', 18.268563, 99.467187, (SELECT id FROM provinces WHERE slug_en='lampang'), NULL),
  ('demo-cafe-lpg-tinn', 'TIN’N', 'TIN’N', 18.284312, 99.494062, (SELECT id FROM provinces WHERE slug_en='lampang'), NULL),
  ('demo-cafe-lpg-wooden', 'Wooden House Cafe', 'Wooden House Cafe', 18.292813, 99.501188, (SELECT id FROM provinces WHERE slug_en='lampang'), NULL),
  ('demo-cafe-lpg-repeat', 'Repeat Café', 'Repeat Café', 18.279812, 99.479438, (SELECT id FROM provinces WHERE slug_en='lampang'), NULL),
  ('demo-cafe-lpg-kin', 'Kin Cafe'' Lampang', 'Kin Cafe'' Lampang', 18.288438, 99.504688, (SELECT id FROM provinces WHERE slug_en='lampang'), NULL),
  ('demo-cafe-lpg-nahiran', 'ณ หิรัญ คาเฟ่ (Na Hiran Cafe)', 'Na Hiran Cafe', 18.283687, 99.504312, (SELECT id FROM provinces WHERE slug_en='lampang'), NULL),
  ('demo-cafe-lpg-himwang', 'Himwang Café', 'Himwang Café', 18.246938, 99.439437, (SELECT id FROM provinces WHERE slug_en='lampang'), NULL),
  ('demo-cafe-lpg-dezato', 'Dezato Cafe', 'Dezato Cafe', 18.284562, 99.496562, (SELECT id FROM provinces WHERE slug_en='lampang'), NULL),
  ('demo-cafe-lpn-jaenghua', 'แจ่งฮั้ว คาเฟ่', 'Jaeng Hua Cafe', 17.8015901, 98.9479395, (SELECT id FROM provinces WHERE slug_en='lamphun'), NULL),
  ('demo-cafe-lpn-me', 'Me Cafe', 'Me Cafe', 17.806593, 98.946506, (SELECT id FROM provinces WHERE slug_en='lamphun'), NULL),
  ('demo-cafe-lpn-tonmai', 'ร้านต้นไม้coffee', 'Tonmai Coffee', 17.8090756, 98.9424361, (SELECT id FROM provinces WHERE slug_en='lamphun'), NULL),
  ('demo-cafe-lpn-chimnom', 'Chimnom Cafe', 'Chimnom Cafe', 17.7894131, 98.9532423, (SELECT id FROM provinces WHERE slug_en='lamphun'), NULL),
  ('demo-cafe-lpn-cafedelyn', 'Cafe De Lyn', 'Cafe De Lyn', 17.8106248, 98.9399172, (SELECT id FROM provinces WHERE slug_en='lamphun'), NULL),
  ('demo-cafe-lpn-lomyen', 'Lomyen Cafe&Bar', 'Lomyen Cafe&Bar', 17.7447667, 99.0236934, (SELECT id FROM provinces WHERE slug_en='lamphun'), NULL),
  ('demo-cafe-lpn-homecoming', 'ร้านกาแฟโฮมคัมมิ่ง', 'Homecoming Coffee', 17.775348, 98.9692228, (SELECT id FROM provinces WHERE slug_en='lamphun'), NULL),
  ('demo-cafe-lpn-natanaoi', 'นาตาน้อย คาเฟ่', 'Na Ta Noi Cafe', 17.8013904, 98.9490251, (SELECT id FROM provinces WHERE slug_en='lamphun'), NULL),
  ('demo-cafe-lpn-kita', 'ร้านกาแฟ คีตา ( KITA COFFEE )', 'KITA COFFEE', 17.7986865, 98.9511664, (SELECT id FROM provinces WHERE slug_en='lamphun'), NULL),
  ('demo-cafe-mhs-madame-ju', 'Madame Ju Coffee', 'Madame Ju Coffee', 19.34765, 98.4357919, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), NULL),
  ('demo-cafe-mhs-dammie', 'Dammie cafe by บ้านมะนาว', 'Dammie Cafe', 19.362038, 98.4495298, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), NULL),
  ('demo-cafe-mhs-ontheway', 'ON THE WAY COFFEE PAI', 'ON THE WAY COFFEE PAI', 19.3577021, 98.4384513, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), NULL),
  ('demo-cafe-mhs-reungrao', 'เรื่องราว Reung-Rao Coffee & Bread', 'Reung-Rao Coffee & Bread', 19.3577707, 98.4410882, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), NULL),
  ('demo-cafe-mhs-pai-studio', 'Pai coffee Studio', 'Pai coffee Studio', 19.3579578, 98.4482754, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), NULL),
  ('demo-cafe-mhs-28nov', '28 November Coffee at pai', '28 November Coffee at Pai', 19.3138556, 98.4441328, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), NULL),
  ('demo-cafe-mhs-hope', 'hope.coffeeandbakery', 'hope.coffeeandbakery', 19.3583673, 98.4406843, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), NULL),
  ('demo-cafe-mhs-carrot', 'Carrot On The Moon', 'Carrot On The Moon', 19.3629277, 98.4393041, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), NULL),
  ('demo-cafe-mhs-chatchai', 'Chatchai Coffee Farming & Roaster', 'Chatchai Coffee Farming & Roaster', 19.3587106, 98.4395653, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'), NULL)
ON CONFLICT (id) DO UPDATE SET
  name_th = EXCLUDED.name_th,
  name_en = EXCLUDED.name_en,
  lat = EXCLUDED.lat,
  lon = EXCLUDED.lon,
  province_id = EXCLUDED.province_id,
  open_hours_json = EXCLUDED.open_hours_json;

-- Hotels
INSERT INTO hotels (id, name_th, name_en, stars, phone, address, lat, lon, province_id) VALUES
  ('demo-hotel-chiangmai-orchid', 'โรงแรมเชียงใหม่ออร์คิด', 'Chiang Mai Orchid', 4, '+66 53 222 099', 'ถ.ห้วยแก้ว ติดห้างกาดสวนแก้ว', 18.7980, 98.9770, (SELECT id FROM provinces WHERE slug_en='chiang-mai')),
  ('demo-hotel-lamphun-river', 'ลำพูนริเวอร์ไซด์', 'Lamphun Riverside Hotel', 3, '+66 53 511 234', 'ริมน้ำปิง เมืองลำพูน', 18.5750, 99.0090, (SELECT id FROM provinces WHERE slug_en='lamphun')),
  ('demo-hotel-lampang-green', 'กรีนการ์เด้น ลำปาง', 'Green Garden Lampang', 4, '+66 54 225 678', 'ใกล้กาดกองต้า', 18.2880, 99.4940, (SELECT id FROM provinces WHERE slug_en='lampang')),
  ('demo-hotel-mhs-river', 'แม่ฮ่องสอนริเวอร์', 'Mae Hong Son Riverfront', 3, '+66 53 612 345', 'ติดลำน้ำปาย อ.เมือง', 19.3020, 97.9710, (SELECT id FROM provinces WHERE slug_en='mae-hong-son')),
  ('demo-hotel-cnx-orchid', 'โรงแรมเชียงใหม่ออคิด', 'Chiang Mai Orchid Hotel', 4, NULL, 'ห้วยแก้ว', 18.7968231, 98.9753703, (SELECT id FROM provinces WHERE slug_en='chiang-mai')),
  ('demo-hotel-cnx-hill', 'โรงแรมเชียงใหม่ฮิลล์', 'Chiang Mai Hill Hotel', 3, NULL, 'ห้วยแก้ว', 18.803983, 98.9620638, (SELECT id FROM provinces WHERE slug_en='chiang-mai')),
  ('demo-hotel-cnx-r2', 'อาร์ทู โฮเทล เชียงใหม่', 'R2 Hotel Chiang Mai', 3, NULL, 'สุเทพ', 18.7877924, 98.9598551, (SELECT id FROM provinces WHERE slug_en='chiang-mai')),
  ('demo-hotel-cnx-premier', 'Premier Hostel Chiang Mai', 'Premier Hostel Chiang Mai', 3, NULL, 'นิมมาน', 18.795871, 98.9843476, (SELECT id FROM provinces WHERE slug_en='chiang-mai')),
  ('demo-hotel-cnx-centara', 'โรงแรมเซ็นทารา ริเวอร์ไซด์ เชียงใหม่', 'Centara Riverside Chiang Mai', 4, NULL, 'ริมปิง', 18.7661385, 99.0048216, (SELECT id FROM provinces WHERE slug_en='chiang-mai')),
  ('demo-hotel-cnx-duangtawan', 'โรงแรมดวงตะวันเชียงใหม่', 'Duangtawan Hotel', 4, NULL, 'ไนท์บาซาร์', 18.7837381, 98.9991495, (SELECT id FROM provinces WHERE slug_en='chiang-mai')),
  ('demo-hotel-cnx-b2-khamtieng', 'โรงแรมบีทู คำเที่ยง บูติค แอนด์ บัดเจท', 'B2 Khamtieng Boutique & Budget', 3, NULL, 'คำเที่ยง', 18.8113485, 98.996709, (SELECT id FROM provinces WHERE slug_en='chiang-mai')),
  ('demo-hotel-cnx-b2-resort', 'B2 Resort Boutique & Budget Hotel', 'B2 Resort Boutique & Budget Hotel', 3, NULL, 'ป่าแดด', 18.8462451, 98.9939219, (SELECT id FROM provinces WHERE slug_en='chiang-mai')),
  ('demo-hotel-cnx-watket', 'โรงแรมวัดเกต เชียงใหม่', 'Wat Ket Hotel', 3, NULL, 'วัดเกต', 18.7921327, 99.0086764, (SELECT id FROM provinces WHERE slug_en='chiang-mai')),
  ('demo-hotel-cnx-white', 'White Boutique Hotel and Spa', 'White Boutique Hotel and Spa', 4, NULL, 'ช้างคลาน', 18.7797836, 98.9942612, (SELECT id FROM provinces WHERE slug_en='chiang-mai')),
  ('demo-hotel-cnx-sriphum', 'ศรีภูมิ เฮอริเอทจ บูทีค เชียงใหม่', 'Sripoom Heritage Boutique', 4, NULL, 'ศรีภูมิ', 18.7962818, 98.9931246, (SELECT id FROM provinces WHERE slug_en='chiang-mai')),
  ('demo-hotel-lpg-space', 'โรงแรมเดอะสเปซ ลำปาง', 'The Space Lampang', 3, NULL, 'เมืองลำปาง', 18.2857948, 99.4859575, (SELECT id FROM provinces WHERE slug_en='lampang')),
  ('demo-hotel-lpg-coconut', 'โรงแรมเดอะ โคโคนัท ลำปาง', 'The Coconut Lampang', 3, NULL, 'เมืองลำปาง', 18.2745477, 99.5119567, (SELECT id FROM provinces WHERE slug_en='lampang')),
  ('demo-hotel-lpg-puangpech', 'Puangpech Hotel (พวงเพชรโฮเทล)', 'Puangpech Hotel', 3, NULL, 'เมืองลำปาง', 18.2917113, 99.5107283, (SELECT id FROM provinces WHERE slug_en='lampang')),
  ('demo-hotel-lpg-b2-city', 'B2 Lampang City Boutique & Budget Hotel', 'B2 Lampang City Boutique & Budget Hotel', 3, NULL, 'เมืองลำปาง', 18.2790366, 99.4891664, (SELECT id FROM provinces WHERE slug_en='lampang')),
  ('demo-hotel-lpg-riverside-guest', 'The Riverside Guest House', 'The Riverside Guest House', 3, NULL, 'เมืองลำปาง', 18.2906214, 99.4942884, (SELECT id FROM provinces WHERE slug_en='lampang')),
  ('demo-hotel-lpg-banmaebunthong', 'โรงแรมบ้านแม่บุญทอง', 'Ban Mae Boon Thong Hotel', 3, NULL, 'เมืองลำปาง', 18.290004, 99.4996141, (SELECT id FROM provinces WHERE slug_en='lampang')),
  ('demo-hotel-lpg-regent', 'Regent Lodge Lampang Hotel', 'Regent Lodge Lampang Hotel', 3, NULL, 'เมืองลำปาง', 18.2914242, 99.5120265, (SELECT id FROM provinces WHERE slug_en='lampang')),
  ('demo-hotel-lpg-rimpan', 'ริมปาน - Rimpan หรือ ริมปานค๊อฟฟี่', 'Rimpan', 3, NULL, 'แจ้ห่ม', 18.6242624, 99.4863358, (SELECT id FROM provinces WHERE slug_en='lampang')),
  ('demo-hotel-lpg-asia', 'เอเซียลำปางโฮเต็ล', 'Asia Lampang Hotel', 3, NULL, 'เมืองลำปาง', 18.2885306, 99.4948272, (SELECT id FROM provinces WHERE slug_en='lampang')),
  ('demo-hotel-lpn-easy2', 'อีซี่โฮเทล ลำพูน 2', 'Easy Hotel Lamphun 2', 3, NULL, 'เมืองลำพูน', 18.5600695, 99.0371993, (SELECT id FROM provinces WHERE slug_en='lamphun')),
  ('demo-hotel-lpn-easy1', 'อีซี่โฮเทล 1 ลำพูน', 'Easy Hotel Lamphun 1', 3, NULL, 'เมืองลำพูน', 18.5734565, 99.0130097, (SELECT id FROM provinces WHERE slug_en='lamphun')),
  ('demo-hotel-lpn-grandpa', 'โรงแรมแกรนด์ ปา แอนด์ รีสอร์ท ลำพูน เชียงใหม่', 'Grand Pa Resort Lamphun', 3, NULL, 'เมืองลำพูน', 18.5598964, 99.0381317, (SELECT id FROM provinces WHERE slug_en='lamphun')),
  ('demo-hotel-lpn-phayainn', 'โรงแรมพญาอิน ลำพูน Phaya Inn', 'Phaya Inn Lamphun', 3, NULL, 'เมืองลำพูน', 18.582971, 99.0157155, (SELECT id FROM provinces WHERE slug_en='lamphun')),
  ('demo-hotel-lpn-norn', 'Nornlamphun Boutique Hotel', 'Nornlamphun Boutique Hotel', 3, NULL, 'เมืองลำพูน', 18.6011899, 99.0202017, (SELECT id FROM provinces WHERE slug_en='lamphun')),
  ('demo-hotel-lpn-189', '189 พรีเมียร์วิลล่าลำพูน', '189 Premier Villa Lamphun', 3, NULL, 'ลี้', 18.5062011, 98.9766159, (SELECT id FROM provinces WHERE slug_en='lamphun')),
  ('demo-hotel-lpn-royalprincess', 'Royal Princess City Hotel Lamphun', 'Royal Princess City Hotel Lamphun', 3, NULL, 'เมืองลำพูน', 18.616082, 99.0349209, (SELECT id FROM provinces WHERE slug_en='lamphun')),
  ('demo-hotel-lpn-place', 'Lamphun Place', 'Lamphun Place', 3, NULL, 'เมืองลำพูน', 18.5838575, 98.994802, (SELECT id FROM provinces WHERE slug_en='lamphun')),
  ('demo-hotel-lpn-firstresident', 'The First Resident Lamphun', 'The First Resident Lamphun', 3, NULL, 'เมืองลำพูน', 18.5897852, 99.0143083, (SELECT id FROM provinces WHERE slug_en='lamphun')),
  ('demo-hotel-mhs-baan-klangdoi', 'บ้านกลางดอย', 'Baan Klang Doi', 3, NULL, 'แม่สะเรียง', 18.81726665, 97.93282704, (SELECT id FROM provinces WHERE slug_en='mae-hong-son')),
  ('demo-hotel-mhs-baan-peeruean', 'บ้านพี่เรือนน้อง', 'Baan Pee Ruean Nong', 3, NULL, 'แม่สะเรียง', 18.83994116, 97.94954195, (SELECT id FROM provinces WHERE slug_en='mae-hong-son')),
  ('demo-hotel-mhs-baan-phutawan', 'บ้านภูตะวัน', 'Baan Phu Tawan', 3, NULL, 'แม่สะเรียง', 18.84621387, 97.95977889, (SELECT id FROM provinces WHERE slug_en='mae-hong-son')),
  ('demo-hotel-mhs-phuchandraeng', 'ภูจันทร์แดง รีสอร์ท', 'Phu Chan Daeng Resort', 3, NULL, 'แม่สะเรียง', 18.84689395, 97.96931836, (SELECT id FROM provinces WHERE slug_en='mae-hong-son')),
  ('demo-hotel-mhs-yoon', 'ยุ้น', 'Yoon', 3, NULL, 'แม่สะเรียง', 18.82463665, 97.93433755, (SELECT id FROM provinces WHERE slug_en='mae-hong-son')),
  ('demo-hotel-mhs-ingsa', 'อิงสระไอหมอก', 'Ing Sa I Mok', 3, NULL, 'แม่สะเรียง', 18.83025084, 97.93513223, (SELECT id FROM provinces WHERE slug_en='mae-hong-son')),
  ('demo-hotel-mhs-inparadisum', 'อินปาราดิซุม', 'In Paradisum', 3, NULL, 'ปาย', 18.83260726, 98.04647115, (SELECT id FROM provinces WHERE slug_en='mae-hong-son')),
  ('demo-hotel-mhs-hern-tai', 'เฮินไต ดาบหาญ', 'Hern Tai Dab Harn', 3, NULL, 'แม่สะเรียง', 18.844313, 97.956187, (SELECT id FROM provinces WHERE slug_en='mae-hong-son')),
  ('demo-hotel-mhs-homestay', 'โฮมสเตย์บ้านเมืองปอน', 'Ban Muang Pon Homestay', 3, NULL, 'ขุนยวม', 18.7406382, 97.92637466, (SELECT id FROM provinces WHERE slug_en='mae-hong-son'))
ON CONFLICT (id) DO UPDATE SET
  name_th = EXCLUDED.name_th,
  name_en = EXCLUDED.name_en,
  stars = EXCLUDED.stars,
  phone = EXCLUDED.phone,
  address = EXCLUDED.address,
  lat = EXCLUDED.lat,
  lon = EXCLUDED.lon,
  province_id = EXCLUDED.province_id;
